[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob = ["*/venv/*", "*/env/*", "*/downloads/*", "*/posts_by_year/*", "*/posts/*"]
known_first_party = ["config", "process_posts", "create_config"]
known_third_party = ["beautifulsoup4", "Pillow", "lxml", "requests", "urllib", "pathlib", "unittest", "tempfile", "shutil", "os", "json", "argparse", "sys", "logging", "time", "io", "hashlib", "re"]
